DROP TABLE IF EXISTS DATA_TREEAGE_TEMP;
CREATE TEMP TABLE IF NOT EXISTS DATA_TREEAGE_TEMP (
CN TEXT,
PLT_CN TEXT,
INVYR INTEGER,
Tree_Age INTEGER,
zoneID TEXT,
US_L3CODE TEXT,
US_L3NAME TEXT,
STATE TEXT
);
COPY DATA_TREEAGE_TEMP (CN,PLT_CN,INVYR,Tree_Age,zoneID,US_L3CODE,US_L3NAME,STATE)
FROM PROGRAM 'sed -s 1d /home/bma09868/data/perseus/FIA/TREEAGE/14775738/*_TREEAGE.csv | cut -d"," -f2- '
DELIMITER ',';

--- Tree_Ageclass5_100 : 1-5=> 5, 6-10=> 10, 11-15=> 15,.... 96+ => 100

DROP TABLE IF EXISTS DATA_TREEAGE;
CREATE TABLE IF NOT EXISTS DATA_TREEAGE AS 
SELECT *, CASE WHEN Tree_Age >= 96 THEN 100 ELSE (((Tree_Age-1) / 5)+1) * 5 END Tree_Ageclass5_100
FROM DATA_TREEAGE_TEMP;
CREATE INDEX DATA_TREEAGE_CN ON DATA_TREEAGE(CN);
