DROP TABLE IF EXISTS DATA_PLOT_FZ;
CREATE TABLE IF NOT EXISTS DATA_PLOT_FZ (
STATECD INTEGER,
UNITCD INTEGER,
COUNTYCD INTEGER,
PLOT INTEGER,
LON TEXT,
LAT TEXT,
DATUM TEXT,
ECOSUBCD TEXT,
ZONE_NUM TEXT
);
COPY DATA_PLOT_FZ (STATECD, UNITCD, COUNTYCD, PLOT, LON, LAT, DATUM, ECOSUBCD, ZONE_NUM)
FROM PROGRAM 'sqlite3 ../FIA_FZ.db "select STATECD, UNITCD, COUNTYCD, PLOT, LON, LAT, DATUM, ECOSUBCD, CAST(ZONE_NUM as INTEGER) ZONE_NUM FROM plot_fz"'
DELIMITER '|';
DROP INDEX IF EXISTS DATA_PLOT_FZ_IDX;
CREATE INDEX DATA_PLOT_FZ_IDX ON DATA_PLOT_EPA(STATECD, UNITCD, COUNTYCD, PLOT);
