DROP INDEX IF EXISTS DATA_PLOT_EPA_IDX;
DROP TABLE IF EXISTS DATA_PLOT_EPA;
CREATE TABLE DATA_PLOT_EPA (
STATECD INTEGER,
UNITCD INTEGER,
COUNTYCD INTEGER,
PLOT INTEGER,
LON TEXT,
LAT TEXT,
DATUM TEXT,
ECOSUBCD TEXT,
EPA_L1 TEXT,
EPA_L2 TEXT,
EPA_L3 TEXT,
EPA_L4 TEXT
);
COPY DATA_PLOT_EPA (STATECD, UNITCD, COUNTYCD, PLOT, LON, LAT, DATUM, ECOSUBCD, EPA_L1, EPA_L2, EPA_L3, EPA_L4)
FROM PROGRAM 'sqlite3 ../FIA_EPA.db "select STATECD, UNITCD, COUNTYCD, PLOT, LON, LAT, DATUM, ECOSUBCD, EPA_L1, EPA_L2, EPA_L3, EPA_L4 FROM plot_epa"'
DELIMITER '|';
CREATE INDEX DATA_PLOT_EPA_IDX ON DATA_PLOT_EPA(STATECD, UNITCD, COUNTYCD, PLOT);
