--- Annual plots, non-skipped measurements, ONLY CONUS (no HAWAII, ALASKA, or islands/territories)
DROP TABLE IF EXISTS DATA_SUBPLOTS;
CREATE TABLE DATA_SUBPLOTS AS
SELECT SUBP.STATECD, SUBP.UNITCD, SUBP.COUNTYCD, SUBP.PLOT, SUBP.SUBP, 
count(*) subp_num_meas,
array_agg(SUBP.PLT_CN ORDER BY SUBP.INVYR) PLT_CNS,
array_agg(SUBP.INVYR ORDER BY SUBP.INVYR) INVYRS,
array_agg(MAKE_DATE(P.MEASYEAR, CAST( P.MEASMON AS INTEGER),  P.MEASDAY) ORDER BY SUBP.INVYR) MEASDATES

FROM PLOT P
JOIN SURVEY SRV ON P.SRV_CN = SRV.CN AND SRV.ANN_INVENTORY = 'Y' AND  -- ANNUAL PLOTS
(P.STATECD <= 56 and P.STATECD <> 2 and P.STATECD <> 15) -- ONLY CONUS
JOIN SUBPLOT SUBP ON P.PLOT_STATUS_CD < 3 AND SUBP.PLT_CN = P.CN AND SUBP.SUBP_STATUS_CD <> 3 --non-skipped
GROUP BY SUBP.STATECD, SUBP.UNITCD, SUBP.COUNTYCD, SUBP.PLOT, SUBP.SUBP;
