BEGIN;
DROP TABLE IF EXISTS DATA_PLOT_ECO;
CREATE TABLE DATA_PLOT_ECO AS

SELECT e.*, f.zone_num
FROM DATA_PLOT_EPA e
LEFT OUTER JOIN DATA_PLOT_FZ f on e.STATECD = f.STATECD AND e.UNITCD = f.UNITCD AND e.COUNTYCD = f.COUNTYCD AND e.PLOT = f.PLOT;
CREATE INDEX DATA_PLOT_ECO_IDX ON DATA_PLOT_ECO(STATECD, UNITCD, COUNTYCD, PLOT);
COMMIT;
