DROP TABLE IF EXISTS DATA_SUBPLOTS_SEEDLINGS;
CREATE TABLE DATA_SUBPLOTS_SEEDLINGS
AS
SELECT 
SD.STATECD, SD.UNITCD, SD.COUNTYCD, SD.PLOT, SD.SUBP,SD.INVYR, SD.PLT_CN, SD.CONDID,
SD.SPCD, SD.SPGRPCD, 
SD.stocking,
SD.TPA_UNADJ,
SD.TOTAGE,
coalesce(SD.TREECOUNT, SD.TREECOUNT_CALC) TREECOUNT,
(P.MANUAL < 2 AND SRV.RSCD != 22 AND SRV.RSCD != 23 AND coalesce(SD.TREECOUNT, SD.TREECOUNT_CALC) <= 6) capped_by_6

FROM DATA_SUBPLOTS_DSTRBS DSD
CROSS JOIN LATERAL unnest(DSD.PLT_CNS , DSD.MEASDATES) sub(plt_cn ,measdate )
JOIN SEEDLING SD ON SD.PLT_CN = sub.plt_cn AND SD.SUBP = DSD.SUBP
JOIN PLOT P on SD.PLT_CN = P.CN
JOIN SURVEY SRV on P.SRV_CN = SRV.CN;
