-- Aggregating TREEs from SUBPLOTS
DROP TABLE IF EXISTS DATA_SUBPLOTS_TREES;
CREATE TABLE DATA_SUBPLOTS_TREES AS
SELECT T.STATECD, T.UNITCD, T.COUNTYCD, T.PLOT, T.SUBP, DSD.subp_num_meas, DSD.subp_has_dstrb, T.TREE, count(*) num_meas,
array_agg(T.CN ORDER BY T.INVYR) TREE_CNS,
array_agg(T.PREV_TRE_CN ORDER BY T.INVYR) PREV_TRE_CNS,
array_agg(T.PLT_CN ORDER BY T.INVYR) PLT_CNS,
array_agg(T.INVYR ORDER BY T.INVYR) INVYRs,
array_agg(T.CONDID ORDER BY T.INVYR) CONDIDS,
array_agg(TA.Tree_Age ORDER BY T.INVYR) AGES,
array_agg(T.SPCD ORDER BY T.INVYR) SPCDs,
array_agg(T.SPGRPCD ORDER BY T.INVYR) SPGRPCDs,
array_agg(T.TPA_UNADJ ORDER BY T.INVYR) TPA_UNADJs,
array_agg(T.DIA ORDER BY T.INVYR) dias, 
array_agg(T.stocking ORDER BY T.INVYR) stockings,
array_agg(CAST(T.totage AS REAL) ORDER BY T.INVYR) TOTAGEs,
array_agg(T.DRYBIO_AG ORDER BY T.INVYR) DRYBIO_AGs,
array_agg(coalesce(T.ACTUALHT, T.HT) ORDER BY T.INVYR) HTs,
array_agg(sub.measdate ORDER BY T.INVYR) measdates,
array_agg(T.STATUSCD ORDER BY T.INVYR) STATUSCDs,
array_agg(T.STANDING_DEAD_CD ORDER BY T.INVYR) STANDING_DEAD_CDs,
array_agg(T.RECONCILECD ORDER BY T.INVYR) RECONCILECDs
 
FROM DATA_SUBPLOTS_DSTRBS DSD
CROSS JOIN LATERAL unnest(DSD.PLT_CNS , DSD.MEASDATES) sub(plt_cn ,measdate )
JOIN TREE T ON T.PLT_CN = sub.plt_cn AND T.SUBP = DSD.SUBP
LEFT OUTER JOIN DATA_TREEAGE TA ON T.CN = TA.CN
GROUP BY T.STATECD, T.UNITCD, T.COUNTYCD, T.PLOT , T.SUBP, DSD.subp_num_meas, DSD.subp_has_dstrb, T.TREE;
