----- repeat for EPA_L3 and ECOSUBCD
DROP TABLE IF EXISTS DATA_SPECIES_EPA_L4_MAP;
CREATE TABLE DATA_SPECIES_EPA_L4_MAP AS
WITH COUNTS AS (
	SELECT EPA.EPA_L4 ECO, T.SPECIES_SYMBOL, T.sftwd_hrdwd , count(*) c 
	FROM DATA_SUBPLOTS_TREES_AGES_CALC T
	JOIN DATA_PLOT_EPA EPA ON
	T.STATECD = EPA.STATECD AND T.UNITCD = EPA.UNITCD AND
	T.COUNTYCD = EPA.COUNTYCD AND T.PLOT = EPA.PLOT
	--T.UNITCD, T.COUNTYCD, T.PLOT, T.SUBP, T.SPCD,
	--WHERE T.STATECD=12 AND T.COUNTYCD IN (125,121,003,023,047)
	GROUP BY ECO, T.SPECIES_SYMBOL, T.sftwd_hrdwd
),
TOTAL AS (
	SELECT ECO, SUM(c) total FROM COUNTS GROUP BY ECO
),
CUMSUMS AS (
	SELECT  COUNTS.ECO, SPECIES_SYMBOL,sftwd_hrdwd,c, 
	(sum(c) OVER (PARTITION BY COUNTS.ECO ORDER BY c DESC, SPECIES_SYMBOL ASC)*100.0/Total.total) cumsum,
	ROW_NUMBER() OVER (PARTITION BY COUNTS.ECO ORDER BY c DESC, SPECIES_SYMBOL ASC) r
	FROM COUNTS
	JOIN TOTAL ON COUNTS.ECO = TOTAL.ECO
	--ORDER BY cumsum ASC,SPECIES_SYMBOL ASC
)

SELECT ECO, SPECIES_SYMBOL, sftwd_hrdwd, c, cumsum , r, 
 (CASE WHEN r > 13 OR CUMSUM > 90.0 OR c < 100  THEN CONCAT(ECO,'_', SFTWD_HRDWD) ELSE SPECIES_SYMBOL END) SPECIES_SYMBOL_MAP
 FROM CUMSUMS
ORDER BY ECO ASC, CUMSUM ASC, SPECIES_SYMBOL ASC;
