DROP TABLE IF EXISTS DATA_ECO_COHORTS;
CREATE TABLE DATA_ECO_COHORTS AS
SELECT T.*, FZ.ZONE_NUM AS FIREZONE, EPA.ECOSUBCD, EPA.EPA_L3, EPA.EPA_L4, SP_MAP_L4.SFTWD_HRDWD, SP_MAP_L4.SPECIES_SYMBOL_MAP as SPECIES_SYMBOL_MAP_L4, SP_MAP_L3.SPECIES_SYMBOL_MAP as SPECIES_SYMBOL_MAP_L3
FROM DATA_COHORTS_DSTRB T
LEFT OUTER JOIN DATA_PLOT_EPA EPA ON
T.STATECD = EPA.STATECD AND T.UNITCD = EPA.UNITCD AND
T.COUNTYCD = EPA.COUNTYCD AND T.PLOT = EPA.PLOT
LEFT OUTER JOIN DATA_PLOT_FZ FZ ON
T.STATECD = FZ.STATECD AND T.UNITCD = FZ.UNITCD AND
T.COUNTYCD = FZ.COUNTYCD AND T.PLOT = FZ.PLOT
LEFT OUTER JOIN DATA_SPECIES_EPA_L4_MAP SP_MAP_L4 ON
T.SPECIES_SYMBOL = SP_MAP_L4.SPECIES_SYMBOL AND SP_MAP_L4.ECO = EPA.EPA_L4
LEFT OUTER JOIN DATA_SPECIES_EPA_L3_MAP SP_MAP_L3 ON
T.SPECIES_SYMBOL = SP_MAP_L3.SPECIES_SYMBOL AND SP_MAP_L3.ECO = EPA.EPA_L3
