BEGIN;
DROP TABLE IF EXISTS DATA_ECO_COHORTS;
CREATE TABLE DATA_ECO_COHORTS AS
SELECT T.*, E.ZONE_NUM AS FIREZONE, E.ECOSUBCD, E.EPA_L3, E.EPA_L4,
  SP_MAP_L4.SPECIES_SYMBOL_MAP as SPECIES_SYMBOL_MAP_L4,
  SP_MAP_L3.SPECIES_SYMBOL_MAP as SPECIES_SYMBOL_MAP_L3,
  SP_MAP_ECOSUBCD.SPECIES_SYMBOL_MAP as SPECIES_SYMBOL_MAP_ECOSUBCD,
  SP_MAP_FZ.SPECIES_SYMBOL_MAP as SPECIES_SYMBOL_MAP_FZ
FROM DATA_COHORTS_DSTRB T
LEFT OUTER JOIN DATA_PLOT_ECO E ON
T.STATECD = E.STATECD AND T.UNITCD = E.UNITCD AND
T.COUNTYCD = E.COUNTYCD AND T.PLOT = E.PLOT
LEFT OUTER JOIN DATA_SPECIES_EPA_L4_MAP SP_MAP_L4 ON
T.SPECIES_SYMBOL = SP_MAP_L4.SPECIES_SYMBOL AND SP_MAP_L4.ECO = E.EPA_L4
LEFT OUTER JOIN DATA_SPECIES_EPA_L3_MAP SP_MAP_L3 ON
T.SPECIES_SYMBOL = SP_MAP_L3.SPECIES_SYMBOL AND SP_MAP_L3.ECO = E.EPA_L3
LEFT OUTER JOIN DATA_SPECIES_ECOSUBCD_MAP SP_MAP_ECOSUBCD ON
T.SPECIES_SYMBOL = SP_MAP_ECOSUBCD.SPECIES_SYMBOL AND SP_MAP_ECOSUBCD.ECO = E.ECOSUBCD
LEFT OUTER JOIN DATA_SPECIES_ZONE_NUM_MAP SP_MAP_FZ ON
T.SPECIES_SYMBOL = SP_MAP_FZ.SPECIES_SYMBOL AND SP_MAP_FZ.ECO = E.ZONE_NUM;
COMMIT;
