DROP TABLE IF EXISTS DATA_ECO_L4_COHORTS;
CREATE TABLE DATA_ECO_L4_COHORTS AS
SELECT T.*, FZ.ZONE_NUM AS FIREZONE, SP_MAP.ECO, SP_MAP.SPECIES_SYMBOL_MAP, SP_MAP.SFTWD_HRDWD
FROM DATA_COHORTS_DSTRB T
LEFT OUTER JOIN DATA_PLOT_EPA EPA ON
T.STATECD = EPA.STATECD AND T.UNITCD = EPA.UNITCD AND
T.COUNTYCD = EPA.COUNTYCD AND T.PLOT = EPA.PLOT
LEFT OUTER JOIN DATA_PLOT_FZ FZ ON
T.STATECD = FZ.STATECD AND T.UNITCD = FZ.UNITCD AND
T.COUNTYCD = FZ.COUNTYCD AND T.PLOT = FZ.PLOT
LEFT OUTER JOIN DATA_SPECIES_EPA_L4_MAP SP_MAP ON
T.SPECIES_SYMBOL = SP_MAP.SPECIES_SYMBOL AND SP_MAP.ECO = EPA.EPA_L4
